### ISSUE TITLE
Navigation not working when going straight to a URL. (update2018)

### ISSUE THREAD

**Issue by icewhite** [coryhouse/pluralsight-redux-app-used-to-build-script#13]
Hi @coryhouse ,

 I've loved doing your pluralsight course and I'm looking at taking your **update2018** branch as a starting point for my application. This is a fantastic resource and I'm delighted you're keeping it up to date, so thanks very much.

On the **update2018** branch, the direct URLs don't appear to be working for me. If I click on the header to navigate to **About** it works fine, but if I point the browser at **/about** (http://localhost:3000/about) it doesn't load the page. This doesn't appear to be an issue on the update branch and I'm struggling to find out what's making the difference.

Any assistance would be greatly appreciated.

Thanks,

Iain

**Comment by icewhite** [comment]
I've worked out the reason - index.html doesn't inclulde the bundle.js file like it does on the update branch. Including it fixes the issue but I'd like to know what adds it on the template when I navigate to "/".

**Comment by coryhouse** [comment]
Thanks! That branch is a work in progress at the moment since I'm using it as a playground for an upcoming course update. That said, get latest. :) Thanks for reporting since I just added in a config for api-history-fallback so loading deep links on dev is supported.

**Comment by icewhite** [comment]
Brilliant - it's working now after taking your update. You are the man!
