### ISSUE TITLE
Possible state mutation in ManageCoursePage.js

### ISSUE THREAD

**Issue by asliwinski** [coryhouse/pluralsight-redux-app-used-to-build-script#2]
I think there is a state mutation occurring in line 33.
https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/blob/master/src/components/course/ManageCoursePage.js#L33

```
32. let course = this.state.course;
33. course[field] = event.target.value;
```

In my app I prepopulate the (analogy) _course_ state using a redux thunk:

```
componentWillReceiveProps(nextProps) {
        if (nextProps.course) this.setState({course: nextProps.course});
}
```

The relevant part of my mapStateToProps function looks as follows:

```
function mapStateToProps(state, ownProps) {

    return {
        course: state.someCourseReducer
    };
}
```

When I start to fill in the form (let's say I type something in the 'title' field), but later navigate away to a page where another dispatch is called, I'm getting the following error:

> A state mutation was detected between dispatches, in the path `someCourseReducer.title`. This may cause incorrect behavior. (http://redux.js.org/docs/Troubleshooting.html#never-mutate-reducer-arguments)

After I change line 32. to:

`32. let course = {...this.state.course};`

the error is gone.

**Comment by coryhouse** [comment]
Merged the PR. Thanks!
