### ISSUE TITLE
The context `router` is marked as required in `Link`, but its value is `undefined`

### ISSUE THREAD

**Issue by BarryArnott** [coryhouse/pluralsight-redux-app-used-to-build-script#23]
Hi Cory,

I'm just working through your brilliant "Building Applications with React and Redux" on Pluralsight and noticed that the course and exercise files have been updated as of 12th March '19.

When downloading the new exercise files, and running them locally via the command 'npm start', things look good from within the IDE (see screenshot 1)

However, I see the following warning in the Chrome dev tools:-

"Warning: Failed context type: The context `router` is marked as required in `Link`, but its value is `undefined`." - (See attached screenshot 2)

This is occurring an all demo files after '03'.

(I realise that this repo is not the repo that is directly related to the new course content uploaded on 12 March '19. However, I couldn't find a repo for the new course content and this repo seemed like the most relevant.)

Cheers,
Barry

![screenshot1](https://user-images.githubusercontent.com/2612173/54492768-44b34c80-48c1-11e9-8e0d-c6f87e12d7a0.png)
![screenshot2](https://user-images.githubusercontent.com/2612173/54492771-4715a680-48c1-11e9-9213-2e0c167c2c1f.png)

**Comment by coryhouse** [comment]
Hi Barry - Can you please share your code on GitHub so I can review it?

**Comment by BarryArnott** [comment]
Hi Cory,

Sure, no problem. Code is shared at: https://github.com/BarryArnott/pluralsight-react-redux

Steps to reproduce are within the repo readme file

**Comment by coryhouse** [comment]
Wow, crazy stuff. So there's a bug in react router 4.3.1. Upgrade to 4.4.0 and it's fixed. I'm patching the course exercise files now. Thanks so much for pointing this out Barry! 💯 Happy coding!

**Comment by BarryArnott** [comment]
No problem at all Cory. Thanks for the unbelievably speedy turnaround!

Keep up the great work on the tutorials :)
