### ISSUE TITLE
No the same code as follow in Pluralsight

### ISSUE THREAD

**Issue by jesspagan** [coryhouse/pluralsight-redux-app-used-to-build-script#24]
I have been struggling for the past week trying to figure how why I was getting so many "Unexpected token" errors trying to use object spread and arrow functions in CoursePage.js as show in the Redux Flow section of the curse.

<img width="503" alt="Screen Shot 2019-04-02 at 9 00 36 PM" src="https://user-images.githubusercontent.com/3449831/55452012-66cbf080-558a-11e9-8e84-c6c8d523b128.png">

After adding plugins, extensions, parsers and trying everything, I just came to see the final version and look what am I missing. This final version does not look like the code shown on the course, there is no use of object spread nor arrow functions and even the HTML looks different. 

I want to check if this code is outdated with the one shown in the actual course and, if that is the case, how to get the right source code for the course.

<img width="890" alt="Screen Shot 2019-04-02 at 8 58 27 PM" src="https://user-images.githubusercontent.com/3449831/55451984-3edc8d00-558a-11e9-9b64-2679902dad49.png">

**Comment by coryhouse** [comment]
Hi - Yes, that's correct. The code in this repo is from the old version of the course. Why are you using the code in this repo? What led you here?

**Comment by jesspagan** [comment]
It was part slides in the course, presented as the base code. I started the course in October but some things came up and I postponed it. When I try to continue where I left, I encountered this situation. Did not notice that the whole course change until I saw the publish date changed to March, 2019.

**Comment by coryhouse** [comment]
Yes, if you check out the pinned comment at the top of the course discussion you'll see a list of changes. Happy coding!
