### ISSUE TITLE
Passing unnecessary second parameter to mockStore

### ISSUE THREAD

**Issue by Und3Rdo9** [coryhouse/pluralsight-redux-app-used-to-build-script#9]
https://github.com/coryhouse/pluralsight-redux-app-used-to-build-script/blob/a66d769cb3966d257a69b4e19bec74d81bfc3f81/src/actions/courseActions.test.js#L56

Currently testing my store using your course as a guide and I'm wondering why you are passing in the expectedActions object you created, while you are also generating the actions by dispatching the actual actions. Wouldn't this be more concise or am I missing a point here?

```
const expectedActions = [
        {type: types.BEGIN_AJAX_CALL},
        {type: types.LOAD_COURSES_SUCCESS, body: {courses: [{id: 'clean-code', title: 'Clean Code'}]}}
      ];
      const store = mockStore({courses: []}, done);
      store.dispatch(courseActions.loadCourses()).then(() => {
        const actions = store.getActions();
        expect(actions).toEqual(expectedActions);
        done();
      });
```

**Comment by coryhouse** [comment]
Yes, you're right, I didn't need to pass that parameter. Thanks for pointing this out!

**Comment by coryhouse** [comment]
Closing since 3/12/19 course update addressed this issue.
